name: Next.js Frontend CI/CD

on:
  push:
    branches:
      - slidingShow
  pull_request:
    branches:
      - slidingShow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Format code with Prettier
        run: npm run format

      - name: Deploy to production
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: .next
